### ISSUE TITLE
Error in shop identification causes crash

### ISSUE THREAD

**Issue by CJYate** [samfoo/noobhack#17]
Hi, I've just found a little problem during item identification in a shop.

If an item goes into inventory slot "A" when I pick it up, when I push the Identify button I get a crash.  
I've tested a couple of other items by adjusting in the inventory, and it seems it's specifically the knapsack position "A" that causes this problem.   The following trace info is given at the command prompt:

Traceback (most recent call last):
  File "/usr/local/bin/noobhack", line 322, in <module>
    curses.wrapper(hack.run)
  File "/usr/lib/python2.6/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "/usr/local/bin/noobhack", line 315, in run
    self._game(window)
  File "/usr/local/bin/noobhack", line 285, in _game
    self.helper.redraw(window, self.options.crumbs)
  File "/usr/local/lib/python2.6/dist-packages/noobhack/ui/helper.py", line 262, in redraw
    if self._things_to_buy_identify() is not None:
  File "/usr/local/lib/python2.6/dist-packages/noobhack/ui/helper.py", line 196, in _things_to_buy_identify
    count = int(count)
ValueError: invalid literal for int() with base 10: 'A'

**Comment by CJYate** [comment]
OK,  sorry. I thought I found this on the tip of noobhack-0.3, but I can't be sure, and can't seem to reproduce just now... I'm looking to write a test that proves the bug if I can reproduce it again in the game - watch this space...

**Comment by samfoo** [comment]
I don't believe this is an issue anymore. Let me know if you see anything like it in the future, though.
